services:

  postgres:
    image: postgres:16
    container_name: pediuber-postgres
    environment:
      POSTGRES_DB: pediuber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pediuber-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  pediuber:
    build:
      context: ./pediuber
      dockerfile: Dockerfile

    container_name: pediuber-backend

    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - rabbitmq

    environment:
      SPRING_PROFILES_ACTIVE: docker

    restart: always

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3