spring.application.name=pediuber

spring.datasource.url=jdbc:postgresql://localhost:5432/pediuber
spring.datasource.username=pediuber
spring.datasource.password=pediuber

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=pediuber
spring.rabbitmq.password=pediuber